version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9f:a9:f8:df:17:c1:60:de:53:97:77:fe:21:c5:e2:d5"
      - checkout
      - run:
          name: Install Harp
          command: sudo npm install --unsafe-perm -g harp

      - deploy:
          name: Deploy
          command: bash ./scripts/deploy.sh
